
name: "08"

on:
  workflow_dispatch:
    inputs:
      echoMessage:
        type: string
        required: false
        description: What should I echo?
      runJob2:
        type: boolean
        required: false
        default: false
        description: Should I run job2?
    
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.echoMessage }}

  job2:
    runs-on: ubuntu-latest
    if: ${{ inputs.runJob2 }} 
    needs: job1
    steps:
      - run: echo job2

  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - run: echo job3
  
  job4:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - run: echo job4

  job5:
    runs-on: ubuntu-latest
    needs: [job3, job4]
    steps:
      - run: echo job5

  testing:
    runs-on: ubuntu-latest
    needs: job1
    environment: test # <==
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm run test

  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - run: echo "generate an artifact" > log.txt
      - uses: actions/upload-artifact@v3
        with:
          name: demo-artifact
          path: log.txt

  download-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: demo-artifact
      - run: cat log.txt
